name: Test Hello World in index.html

on: [push, pull_request]

jobs:
  check-hello-world:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3

      # Run a test to check if index.html contains "Hello World"
      - name: Check for "Hello World" in index.html
        run: |
          if grep -q "background" index.html; then
            echo "Test passed: 'background' found in index.html"
          else
            echo "Test failed: 'background' not found in index.html"
            exit 1
          fi
