name: Test Flask App

on: [push, pull_request]

jobs:
  test-flask-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Start Flask app
        run: |
          python health.py &
      
      - name: Wait for server to start
        run: sleep 10

      - name: Test health check endpoint
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:5000/catalog/health | grep -q ' "status": "ok" '; then
              echo "Test passed: Health check endpoint returned 'status: ok'"
              break
            fi
            echo "Test failed: Health check endpoint did not return 'status: ok'"
            sleep 1
          done
